// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2u7FeJtaeov07JsDEQQUi9ieX5cN_xRg',
    appId: '1:307192909597:web:12320baccf85b583861bf4',
    messagingSenderId: '307192909597',
    projectId: 'teachly-w',
    authDomain: 'teachly-w.firebaseapp.com',
    storageBucket: 'teachly-w.firebasestorage.app',
    measurementId: 'G-11MCK7CNBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTvKxU9FTSaYQJ8cIIoms4q1cnJJHLD8',
    appId: '1:307192909597:android:ae073edebed99168861bf4',
    messagingSenderId: '307192909597',
    projectId: 'teachly-w',
    storageBucket: 'teachly-w.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIXQvaeAR1CvqVnBTS9HnoRe6QJx1rvzU',
    appId: '1:307192909597:ios:411954b467a0d591861bf4',
    messagingSenderId: '307192909597',
    projectId: 'teachly-w',
    storageBucket: 'teachly-w.firebasestorage.app',
    iosBundleId: 'com.example.teachly',
  );
}
